name: Build and deploy PHP app to Azure Web App - magistralfarma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Limpiar cachés y optimizar Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link || true
          chmod -R 775 storage bootstrap/cache

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*.git*" "*node_modules*" "*.github*" "tests*" "test-azure-connection.php" "test-simple.php"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_64B86074F9F048679E0D93FFEFA7E214 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C17490A7C258455FAE3889FC8EF56E5A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9DC44F8B9D04BFC8533133CC429B8F5 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'magistralfarma'
          slot-name: 'Production'
          package: .
